// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class AdAstra
{
        public const string achievement_spaceman = "CggIh8-wu3AQAhAC"; // <GPGSID>
        public const string achievement_tough_guy = "CggIh8-wu3AQAhAK"; // <GPGSID>
        public const string achievement_ares = "CggIh8-wu3AQAhAI"; // <GPGSID>
        public const string achievement_apollo = "CggIh8-wu3AQAhAJ"; // <GPGSID>
        public const string achievement_poland_can_into_space = "CggIh8-wu3AQAhAB"; // <GPGSID>
        public const string achievement_alien = "CggIh8-wu3AQAhAD"; // <GPGSID>
        public const string achievement_moonwalker = "CggIh8-wu3AQAhAE"; // <GPGSID>
        public const string achievement_saturn = "CggIh8-wu3AQAhAG"; // <GPGSID>
        public const string achievement_atlas = "CggIh8-wu3AQAhAH"; // <GPGSID>
        public const string achievement_sputnik = "CggIh8-wu3AQAhAA"; // <GPGSID>
        public const string achievement_autopilot = "CggIh8-wu3AQAhAF"; // <GPGSID>
        public const string leaderboard_score = "CggIh8-wu3AQAhAL"; // <GPGSID>

}

